Evil 31 add edit reservation modal
Spolka-Zlo/D17Map-Mobile pull request #13
Opened 2024-11-10 08:33 UTC by yoinker57

2024-11-10 20:12 UTC, irosikoni requested changes

2024-11-10 20:12 UTC, irosikoni commented on app/(tabs)/reservation/index.tsx
> +    const [reservation, setReservation] = useState<Reservation | null>(null)
I have an error here:
![image](https://github.com/user-attachments/assets/a45d4c16-8973-428a-a0b3-915486d4480a)

2024-11-10 20:12 UTC, irosikoni commented on bun.lockb
still worried that this file is updated after every bun install

2024-11-10 20:12 UTC, irosikoni commented on components/reservation_components/EditReservationComponent.tsx
> +                                            valueField={'value'}
![image](https://github.com/user-attachments/assets/ec8de9c7-52bd-4667-a3d0-46140a7b758b)

2024-11-10 22:25 UTC, yoinker57 commented on app/(tabs)/reservation/index.tsx
> +    const [reservation, setReservation] = useState<Reservation | null>(null)
done

2024-11-10 22:25 UTC, yoinker57 commented on components/reservation_components/EditReservationComponent.tsx
> +                                            valueField={'value'}
done

2024-11-14 00:20 UTC, irosikoni approved these changes
![462650699_1215070449602625_3995049300764157572_n](https://github.com/user-attachments/assets/26cd4073-8b88-444b-8351-dbb5913712b1)
Get rid of this warning.

![462638470_3915827248654440_1499740856124662614_n](https://github.com/user-attachments/assets/7de8de12-ee95-4abc-8655-d41cf5bd9354)

Change the size of this dropdown menu.

Also, after removing reservation, the modal should automatically close.

2024-11-14 09:10 UTC, merged